import React, { useEffect, useState } from 'react';
import { Lock, FileText, Shield, Activity, ArrowUpRight, Database, FileCode } from 'lucide-react';
import { User, Invention } from '../types';
import { getUserInventions } from '../services/firebaseService';

interface DashboardProps {
  user: User;
  onNavigate: (page: string) => void;
}

const StatCard = ({ icon: Icon, title, value, sub, colorClass, onClick }: any) => (
  <div 
    onClick={onClick}
    className="bg-cardbg border border-slate-800 rounded-xl p-6 cursor-pointer hover:border-slate-600 hover:shadow-lg hover:shadow-slate-900/50 transition-all duration-300 group"
  >
    <div className="flex items-start justify-between mb-4">
      <div className={`p-3 rounded-lg bg-slate-800/50 ${colorClass} group-hover:scale-110 transition-transform`}>
        <Icon size={24} />
      </div>
      <ArrowUpRight size={20} className="text-slate-600 group-hover:text-white" />
    </div>
    <h3 className="text-3xl font-bold text-white mb-1">{value}</h3>
    <p className="text-slate-400 font-medium mb-1">{title}</p>
    <p className="text-xs text-slate-500">{sub}</p>
  </div>
);

export const Dashboard: React.FC<DashboardProps> = ({ user, onNavigate }) => {
  const [inventions, setInventions] = useState<Invention[]>([]);

  useEffect(() => {
    if (user.uid) {
      getUserInventions(user.uid).then(setInventions);
    }
  }, [user]);

  const downloadHash = (fileName: string, hash: string) => {
    const content = `Filename: ${fileName}\nSHA-256 Fingerprint: ${hash}\nGenerated by Authenta\nDate: ${new Date().toISOString()}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.hash.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in">
      <div>
        <h2 className="text-3xl font-bold text-white mb-2">Welcome back, {user.name}</h2>
        <p className="text-slate-400">Your secure Authenta workspace is ready.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <StatCard 
          icon={Database} 
          title="Vault Items" 
          value={inventions.length} 
          sub="Encrypted in Cloud" 
          colorClass="text-neon-400"
          onClick={() => onNavigate('vault')}
        />
        <StatCard 
          icon={FileText} 
          title="AI Tools" 
          value="Access" 
          sub="Rewrite & Grammar" 
          colorClass="text-purple-400"
          onClick={() => onNavigate('rewrite')}
        />
        <StatCard 
          icon={Shield} 
          title="Integrity" 
          value="Tools" 
          sub="Hash & Verify" 
          colorClass="text-emerald-400"
          onClick={() => onNavigate('hashtools')}
        />
      </div>

      <div className="bg-cardbg border border-slate-800 rounded-xl p-6">
        <div className="flex items-center gap-2 mb-6">
          <Activity size={20} className="text-neon-400" />
          <h3 className="text-lg font-semibold text-white">Recent Vault Activity</h3>
        </div>
        
        <div className="space-y-4">
          {inventions.slice(0, 5).map((inv) => (
            <div key={inv.id} className="flex flex-col md:flex-row md:items-center justify-between p-4 rounded-lg bg-slate-800/30 border border-slate-800/50 hover:bg-slate-800/50 transition-colors">
              <div className="flex items-center gap-4 mb-3 md:mb-0">
                <div className="w-2 h-2 rounded-full bg-neon-400 shadow-[0_0_8px_rgba(0,243,255,0.5)]"></div>
                <div>
                  <p className="text-sm font-medium text-white">{inv.title}</p>
                  <p className="text-xs text-slate-500">{inv.license} • {(inv.fileSize / 1024).toFixed(1)} KB</p>
                </div>
              </div>
              
              <div className="flex items-center gap-3">
                 <button 
                    onClick={(e) => { e.stopPropagation(); downloadHash(inv.fileName, inv.hash); }}
                    className="flex items-center gap-1 px-3 py-1.5 rounded text-xs font-medium bg-slate-800 text-slate-300 hover:text-white hover:bg-slate-700 transition-colors border border-slate-700"
                    title="Download Hash Fingerprint"
                 >
                   <FileCode size={12} /> Fingerprint
                 </button>
                 <span className="text-xs font-mono text-neon-400 bg-neon-900/50 px-2 py-1 rounded border border-neon-500/20">ENCRYPTED</span>
              </div>
            </div>
          ))}
          {inventions.length === 0 && (
            <p className="text-slate-500 text-sm italic">No recent activity.</p>
          )}
        </div>
      </div>
    </div>
  );
};